export const PUBLICATIONS = [
  { id: 1, title: "Autonomous Path-Finding for Multi-Axis Robotic Extrusion", authors: "Member 1, Member 4", venue: "ICRA 2025", memberIds: [1, 4], labId: 'tech', projectId: 'p1', year: 2025 },
  { id: 2, title: "Latent Space Exploration in Fungal Growth Patterns", authors: "Member 2, Member 3", venue: "Nature Biotech", memberIds: [2, 3], labId: 'additive', projectId: 'p5', year: 2025 },
  { id: 3, title: "Quantum-Accelerated Topology Optimization for Lattice Structures", authors: "Member 1, Member 2", venue: "Journal of Computational Design", memberIds: [1, 2], labId: 'quantum', projectId: 'p9', year: 2025 },
  { id: 4, title: "Haptic Feedback Loops in Remote Robotic Masonry", authors: "Member 4", venue: "ACADIA 2024", memberIds: [4], labId: 'tech', projectId: 'p13', year: 2024 },
  { id: 5, title: "Bias Mitigation in Generative Architectural Transformers", authors: "Member 1", venue: "NeurIPS 2024", memberIds: [1], labId: 'ai', projectId: 'p16', year: 2024 },
  { id: 6, title: "Graphene-Augmented Polymers for Large-Scale Additive Manufacturing", authors: "Member 3, Member 4", venue: "Advanced Materials", memberIds: [3, 4], labId: 'additive', projectId: 'p19', year: 2024 },
  { id: 7, title: "Non-Linear Kinematics in Responsive Building Envelopes", authors: "Member 1, Member 4", venue: "Smart Materials and Structures", memberIds: [1, 4], labId: 'tech', projectId: 'p1', year: 2023 },
  { id: 8, title: "Deep Reinforcement Learning for Adaptive Robotic Gripping", authors: "Member 1", venue: "CVPR 2025", memberIds: [1], labId: 'ai', projectId: 'p2', year: 2025 },
  { id: 9, title: "Mycelium as a Structural Scaffold: Mechanical Characterization", authors: "Member 2", venue: "Bio-Design Journal", memberIds: [2], labId: 'additive', projectId: 'p5', year: 2023 },
  { id: 10, title: "Cryogenic Printing: Material Phase Transitions at Scale", authors: "Member 4, Member 2", venue: "Quantum Fabrication Quarterly", memberIds: [2, 4], labId: 'quantum', projectId: 'p12', year: 2024 },
  { id: 11, title: "Gesture-Based Interface Protocols for Industrial Kuka Arms", authors: "Member 3", venue: "CHI 2024", memberIds: [3], labId: 'tech', projectId: 'p13', year: 2024 },
  { id: 12, title: "Solar-Harvesting Textiles via Robotic Weaving Processes", authors: "Member 2, Member 1", venue: "Sustainable Design Review", memberIds: [1, 2], labId: 'tech', projectId: 'p17', year: 2023 },
  { id: 13, title: "Acoustic Meta-Surfaces: Geometry-Induced Sound Absorption", authors: "Member 3", venue: "Applied Physics Letters", memberIds: [3], labId: 'additive', projectId: 'p18', year: 2022 },
  { id: 14, title: "Urban Network Optimization via Quantum Annealing", authors: "Member 2, Member 3", venue: "Smart Cities Journal", memberIds: [2, 3], labId: 'ai', projectId: 'p20', year: 2023 },
  { id: 15, title: "Soft-Robotic Actuators for Collaborative Assembly Tasks", authors: "Member 4", venue: "Robotics and Automation", memberIds: [4], labId: 'tech', projectId: 'p3', year: 2024 },
  { id: 16, title: "Diffusion Models for Synthetic Urban Morphology", authors: "Member 1, Member 2", venue: "SIGGRAPH 2025", memberIds: [1, 2], labId: 'ai', projectId: 'p14', year: 2025 },
  { id: 17, title: "Tensile Strength Variability in 3D Printed Bio-Polymers", authors: "Member 3", venue: "Additive Manufacturing Journal", memberIds: [3], labId: 'additive', projectId: 'p8', year: 2022 },
  { id: 18, title: "Quantum Probability Fields in Wind-Load Simulations", authors: "Member 1, Member 3", venue: "Journal of Fluid Mechanics", memberIds: [1, 3], labId: 'quantum', projectId: 'p11', year: 2023 },
  { id: 19, title: "VR-Enabled Design Sandboxes for Multi-Stakeholder Planning", authors: "Member 3, Member 4", venue: "CAADRIA 2024", memberIds: [3, 4], labId: 'tech', projectId: 'p15', year: 2024 },
  { id: 20, title: "Reciprocal Trust in Human-Robot Architectural Assembly", authors: "Member 1, Member 4", venue: "HRI 2025", memberIds: [1, 4], labId: 'ai', projectId: 'p16', year: 2025 },
  { id: 21, title: "Variable Stiffness in Pneumatic Robotic Skins", authors: "Member 4", venue: "Soft Robotics Journal", memberIds: [4], labId: 'tech', projectId: 'p3', year: 2022 },
  { id: 22, title: "Real-Time Error Correction in Large-Scale 3D Printing", authors: "Member 3, Member 1", venue: "Robotic Fabrication in Architecture", memberIds: [1, 3], labId: 'additive', projectId: 'p6', year: 2023 },
  { id: 23, title: "Quantum Search Algorithms for Structural Design Space", authors: "Member 1", venue: "Computational Intelligence", memberIds: [1], labId: 'quantum', projectId: 'p9', year: 2021 },
  { id: 24, title: "Bio-Ink Extrusion Rheology for Photosynthetic Algae", authors: "Member 3, Member 2", venue: "Biotechniques", memberIds: [2, 3], labId: 'additive', projectId: 'p6', year: 2022 },
  { id: 25, title: "Multi-Agent Coordination for On-Site Construction Robots", authors: "Member 2", venue: "Automated Construction", memberIds: [2], labId: 'quantum', projectId: 'p10', year: 2023 },
  { id: 26, title: "Topology-Aware Mesh Refinement using GNNs", authors: "Member 4, Member 1", venue: "AI in Design", memberIds: [1, 4], labId: 'ai', projectId: 'p14', year: 2024 },
  { id: 27, title: "SMA Actuators in Kinetic Tensegrity Systems", authors: "Member 1, Member 4", venue: "Journal of IASS", memberIds: [1, 4], labId: 'tech', projectId: 'p1', year: 2021 },
  { id: 28, title: "Superconducting Material Behavior in Quantum Computing Frames", authors: "Member 2", venue: "Quantum Science", memberIds: [2], labId: 'quantum', projectId: 'p12', year: 2022 },
  { id: 29, title: "Ethics of Generative Adversarial Networks in Public Space", authors: "Member 1, Member 4", venue: "Philosophy and Technology", memberIds: [1, 4], labId: 'ai', projectId: 'p16', year: 2023 },
  { id: 30, title: "Robotic Weaving of Carbon-Fiber Reinforcement", authors: "Member 2", venue: "Composite Structures", memberIds: [2], labId: 'tech', projectId: 'p17', year: 2022 },
  { id: 31, title: "3D Printed Metamaterials for Low-Frequency Noise Control", authors: "Member 3", venue: "Acoustical Society of America", memberIds: [3], labId: 'additive', projectId: 'p18', year: 2021 },
  { id: 32, title: "Integrating Graphene into FDM Feedstock", authors: "Member 1", venue: "Nanotech Today", memberIds: [1], labId: 'additive', projectId: 'p19', year: 2022 },
  { id: 33, title: "Quantum Annealing for Dynamic Transit Network Layout", authors: "Member 2, Member 3", venue: "Traffic Research", memberIds: [2, 3], labId: 'quantum', projectId: 'p20', year: 2024 },
  { id: 34, title: "Latency Reduction in Visual-Inertial Odometry for UAVs", authors: "Member 1", venue: "Sensors and Actuators", memberIds: [1], labId: 'ai', projectId: 'p2', year: 2021 },
  { id: 35, title: "Structural Integrity of Mycelium-Composite Panels", authors: "Member 2, Member 3", venue: "Construction and Building Materials", memberIds: [2, 3], labId: 'additive', projectId: 'p5', year: 2022 },
  { id: 36, title: "Cellular Matrices for Osteoblast Proliferation in Lattices", authors: "Member 2", venue: "Bio-Materials Journal", memberIds: [2], labId: 'tech', projectId: 'p7', year: 2021 },
  { id: 37, title: "Starch-Based Resin: A Lifecycle Analysis in 3D Printing", authors: "Member 3", venue: "Circular Economy Review", memberIds: [3], labId: 'additive', projectId: 'p8', year: 2023 },
  { id: 38, title: "Entanglement-Based Secure Communication for Design Teams", authors: "Member 2", venue: "Quantum Networks", memberIds: [2], labId: 'quantum', projectId: 'p10', year: 2022 },
  { id: 39, title: "Simulating Turbulent Flow using Variational Quantum Eigensolvers", authors: "Member 1, Member 3", venue: "Physical Review E", memberIds: [1, 3], labId: 'quantum', projectId: 'p11', year: 2023 },
  { id: 40, title: "Hand-Tracking Precision in High-Payload Robotic Tasks", authors: "Member 3", venue: "IEEE Transactions on Haptics", memberIds: [3], labId: 'tech', projectId: 'p13', year: 2021 },
  { id: 41, title: "Human-in-the-Loop Refinement of Generative Floorplans", authors: "Member 4", venue: "Design Studies", memberIds: [4], labId: 'ai', projectId: 'p14', year: 2022 },
  { id: 42, title: "Spatial Cognition in Collaborative VR Environments", authors: "Member 3, Member 4", venue: "Virtual Reality Journal", memberIds: [3, 4], labId: 'tech', projectId: 'p15', year: 2023 },
  { id: 43, title: "Dataset Diversity for Non-Western Architectural Styles", authors: "Member 1", venue: "FAccT 2025", memberIds: [1], labId: 'ai', projectId: 'p16', year: 2025 },
  { id: 44, title: "Passive Cooling via Geometry-Optimized 3D Printed Ceramics", authors: "Member 3", venue: "Architectural Science Review", memberIds: [3], labId: 'additive', projectId: 'p18', year: 2022 },
  { id: 45, title: "Nano-Additive Influence on Glass Transition Temperature", authors: "Member 4", venue: "Polymer Science", memberIds: [4], labId: 'additive', projectId: 'p19', year: 2021 },
  { id: 46, title: "Quantum-Inspired Algorithms for Power Grid Resiliency", authors: "Member 2", venue: "Smart Grid Journal", memberIds: [2], labId: 'quantum', projectId: 'p20', year: 2023 },
  { id: 47, title: "Tactile-Driven Surface Finishing for Robotic Carpentry", authors: "Member 1, Member 2", venue: "Robotics and CIM", memberIds: [1, 2], labId: 'tech', projectId: 'p4', year: 2022 },
  { id: 48, title: "Photosynthetic Performance of Algae-Embedded Hydrogels", authors: "Member 3", venue: "Journal of Biological Engineering", memberIds: [3], labId: 'additive', projectId: 'p6', year: 2021 },
  { id: 49, title: "3D Printing Scaffolds for Tissue Engineering Applications", authors: "Member 2, Member 3", venue: "Biotechnology Progress", memberIds: [2, 3], labId: 'tech', projectId: 'p7', year: 2020 },
  { id: 50, title: "High-Frequency SMA Response for Micro-Kinetic Facades", authors: "Member 1, Member 4", venue: "Sensors and Structures", memberIds: [1, 4], labId: 'tech', projectId: 'p1', year: 2020 }
];